# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 09:50
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20180618_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='education'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='work',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='work'),
        ),
    ]
